image: docker:cli

services:
  - docker:dind

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - docker build -t hikaruvi/images/univer-simpleapi-app .

test-job:
  stage: test
  script:
    - >
      docker run --rm hikaruvi/images/univer-simpleapi-app
      ./test.sh
