apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-app
    owner: ip314s21
spec:
  selector:
    app: {{ .Release.Name }}-app
    owner: ip314s21
  ports:
    - port: 80
      targetPort: {{ .Values.ports.containerPort }}
      protocol: TCP
  type: ClusterIP
